### PR TITLE
Quick Draft of Resize

### PR DESCRIPTION
**Pull request by DawnTheWitch**

### CODE REVIEW

**Comment by DawnTheWitch** [comment]
image
Helper Function for this?

**Comment by James-Oswald** [comment]
Still has some insert things to be worked out
image

**Comment by James-Oswald** [comment]
Its possible the above issue is actually due to #204, we should wait to see if this resolves it.

**Comment by DawnTheWitch** [comment]
> Its possible the above issue is actually due to #202 and being addressed by #204 we should wait to see if this resolves it.

This seems to now be resolved with what Anusha has added

**Review by James-Oswald — APPROVED** [review]
We still need to extend this to allow for more robust resizing, such as extending to the left rather than the right.

**Review by James-Oswald — APPROVED** [review]

**Pull request merged**
